## What is Numpy?

Numpy: To compute everything in Linear Algebra and a little bit of probablity
Central Core: Numpy array
Question:
1 - difference with List?
2 - Why do we need it?
3 - Benefits?

Array in Numpy: Scalar, 1D, 2D, (ndarray), Matrix, Tensor
--------------------------------------

Applications of Numpy Module:
1 - Linear Regression
2 - Logistic Regression
3 - Deep Neural Networks (Everything in Deep Learning)
4 - K-Means
5 - Density Estimation
6 - Principle Component Analysis (PCA) -> Dimensionality Reduction : ICA
7 - Matrix Factorization -> Recommender System : NNMF
8 - SVM
9 - Markov Models -> HMM
10 - Control Systems
11 - Game Theory
12 - Optimization Theory
13 - profile Optimization



## NumPy array creation functions

In [1]:
import numpy as np
from time import time
import sys

In [2]:
a1D = np.array([1, 2, 3, 4])
a1D

array([1, 2, 3, 4])

In [4]:
a2D = np.array([[1, 2], [3, 4]])
a2D

array([[1, 2],
       [3, 4]])

In [74]:
a3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
a3D

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [76]:
a = np.array([127, 128, 129, 260], dtype=np.int8)
a

array([ 127, -128, -127,    4], dtype=int8)

In [77]:
a = np.array([2, 3, 4], dtype=np.uint32)
b = np.array([5, 6, 7], dtype=np.uint32)
c_unsigned32 = a - b
print('unsigned c:', c_unsigned32, c_unsigned32.dtype)

unsigned c: [4294967293 4294967293 4294967293] uint32


In [78]:
c_signed64 = a - b.astype(np.int32)
print('signed c:', c_signed64, c_signed64.dtype)

signed c: [-3 -3 -3] int64


In [79]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
np.arange(2, 10, dtype=float)

array([2., 3., 4., 5., 6., 7., 8., 9.])

In [81]:
np.arange(2, 3, 0.1)

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

In [82]:
np.linspace(1., 4., 6)

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

In [83]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [84]:
np.eye(3, 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [86]:
np.diag([1, 2, 10])

array([[ 1,  0,  0],
       [ 0,  2,  0],
       [ 0,  0, 10]])

In [90]:
np.diag([1, 2, 3], 1)

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

In [95]:
x = np.arange(9.0).reshape(3, 3)
x

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [97]:
np.diag(x)

array([0., 4., 8.])

In [98]:
a = np.array([[1, 2], [3, 4]])
np.diag(a)

array([1, 4])

In [99]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [100]:
np.zeros((2, 3, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [101]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [102]:
np.ones((2, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [103]:
a = np.array([1, 2, 3, 4, 5, 6])   # Numpy arrays are mutable
b = a[:2]
b += 1
print('a =', a, '; b =', b)

a = [2 3 3 4 5 6] ; b = [2 3]


In [104]:
a = np.array([1, 2, 3, 4])
b = a[:2].copy()
b += 1
print('a = ', a, 'b = ', b)

a =  [1 2 3 4] b =  [2 3]


In [105]:
A = np.ones((2, 2))
B = np.eye(2, 2)
C = np.zeros((2, 2))
D = np.diag((-3, -4))
np.block([[A, B], [C, D]])

array([[ 1.,  1.,  1.,  0.],
       [ 1.,  1.,  0.,  1.],
       [ 0.,  0., -3.,  0.],
       [ 0.,  0.,  0., -4.]])

In [106]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [107]:
a = np.array((1,2,3))
b = np.array((4,5,6))
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [108]:
x = np.arange(9.0)
np.split(x, 3)

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]

In [111]:
y = np.arange(16.0).reshape(4, 4)
y

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [112]:
np.split(y, 2, axis=1)

[array([[ 0.,  1.],
        [ 4.,  5.],
        [ 8.,  9.],
        [12., 13.]]),
 array([[ 2.,  3.],
        [ 6.,  7.],
        [10., 11.],
        [14., 15.]])]

In [114]:
x = np.arange(8.0)
np.split(x, [3, 5, 6, 10])

[array([0., 1., 2.]),
 array([3., 4.]),
 array([5.]),
 array([6., 7.]),
 array([], dtype=float64)]

In [115]:
x = np.arange(16.0).reshape(4, 4)
x

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [116]:
np.hsplit(x, 2)

[array([[ 0.,  1.],
        [ 4.,  5.],
        [ 8.,  9.],
        [12., 13.]]),
 array([[ 2.,  3.],
        [ 6.,  7.],
        [10., 11.],
        [14., 15.]])]

In [117]:
np.vsplit(x, 2)

[array([[0., 1., 2., 3.],
        [4., 5., 6., 7.]]),
 array([[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])]

## Arrays vs Lists

NumPy Arrays are generally faster than Python Lists:

1 - Array: a collection of homogeneous data-types, stored in contiguous memory locations
2 - List: a collection of heterogeneous data types, stored in non-contiguous memory locations.
2 - NumPy breaks down a task into multiple fragments and then processes all the fragments in parallel
3 - NumPy integrates C, C++, and Fortran codes in Python => very little execution time compared to Python.

In [118]:
L = [1,2,3]

In [119]:
A = np.array([1,2,3])

In [120]:
for e in L:
  print(e)

1
2
3


In [121]:
for e in A:
  print(e)

1
2
3


In [122]:
L.append(4)

In [123]:
L

[1, 2, 3, 4]

In [124]:
A.append(4) # doesn't work, append exists in the module level, not in arrays

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [125]:
L + [5]

[1, 2, 3, 4, 5]

In [126]:
A + np.array([4])

array([5, 6, 7])

In [127]:
A + np.array([4,5,6])

array([5, 7, 9])

In [128]:
A + np.array([4,5]) # doesn't work

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [129]:
2 * A

array([2, 4, 6])

In [130]:
2 * L

[1, 2, 3, 4, 1, 2, 3, 4]

In [131]:
L + L

[1, 2, 3, 4, 1, 2, 3, 4]

In [133]:
L2 = []
for e in L:
  L2.append(e + 3)

In [134]:
L2

[4, 5, 6, 7]

In [135]:
L2 = [e + 3 for e in L]

In [ ]:
L2

In [136]:
L2 = []
for e in L:
  L2.append(e**2)

In [ ]:
L2

In [137]:
A**2

array([1, 4, 9])

In [138]:
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081])

In [139]:
np.log(A)

array([0.        , 0.69314718, 1.09861229])

In [140]:
np.exp(A)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [ ]:
np.tanh(A)

In [142]:
# Test to compare List and Array
numpy_array = np.random.rand(1000000)
list_conv = list(numpy_array)

In [143]:
start1 = time()
numpy_mean = np.mean(numpy_array)
print(f"Computing the mean using NumPy: {numpy_mean}")
end1 = time()
time1 = end1 - start1
print(f"Computation time: {time1}")

Computing the mean using NumPy: 0.5000947341583862
Computation time: 0.004998683929443359


In [144]:
start2 = time()
list_mean = np.mean(list_conv)
print(f"Computing the mean using lists: {list_mean}")
end2 = time()
time2 = end2 - start2
print(f"Computation time: {time2}")

Computing the mean using lists: 0.5000947341583862
Computation time: 0.1209249496459961


In [145]:
assert abs(numpy_mean - list_mean) <= 10e-6, "Alert, means are not equal"

In [146]:
# Numpy Slower than List
def numpy_append():
    arr = np.empty((1, 0), int)
    for i in range(100000):
        arr = np.append(arr, np.array(i))
    return arr

In [147]:
def list_append():
    list_1 = []
    for i in range(100000):
        list_1.append(i)
    return list_1

In [148]:
def main ():

    start1 = time()
    new_np_arr = numpy_append()
    end1 = time()
    print(f"Computation time of the numpy array : {end1 - start1}")

    start2 = time()
    new_list = list_append()
    end2 = time()
    print(f"Computation time of the list: {end2 - start2}")

    assert list(new_np_arr) == new_list, "Arrays tested are not the same"

In [149]:
if __name__ == "__main__":
    main()

Computation time of the numpy array : 4.460419416427612
Computation time of the list: 0.006995201110839844


"Append values to the end of an array.
    Parameters
    ----------
    arr : array_like
        Values are appended to a copy of this array.
    values : array_like
        These values are appended to a copy of `arr`.  It must be of
        the correct shape (the same shape as `arr`, excluding
        `axis`). If `axis` is not specified, `values` can be any
        shape and will be flattened before use.
    axis : int, optional
        The axis along which `values` are appended.  If `axis` is
        not given, both `arr` and `values` are flattened before use.
    Returns
    -------
    append : ndarray
        A copy of `arr` with `values` appended to `axis`.  Note that
        `append` does not occur in-place: a new array is allocated
        and filled.  If `axis` is None, `out` is a flattened array."

## Deque and Comparison to List

https://dev.to/v_it_aly/python-deque-vs-listwh-25i9


In [150]:
S = range(1000)
print("Size of the whole list in bytes: ",sys.getsizeof(list(S)))
D = np.arange(1000)
print("Size of the whole list in bytes: ",sys.getsizeof(D))

Size of the whole list in bytes:  8056
Size of the whole list in bytes:  4112


In [157]:
l1 = list(range(10))
l2 = [0, 1, 2, 3, 4, 5, 6 ,7, 8, 9, 10, 11, 12, 13, 14, 15, 16]
print(sys.getsizeof(l1) == sys.getsizeof(l2))
print(f'l1: {sys.getsizeof(l1)},  l2:{sys.getsizeof(l2)}')

False
l1: 136,  l2:216


## The Dot Product

$$ a \cdot b = a^T b = \sum_{d=1}^D a_d b_d $$

In [3]:
a = np.array([1,2])
b = np.array([3,4])

In [4]:
dot = 0
for e, f in zip(a, b):
  dot += e*f
dot

11

In [5]:
# use integer index
dot = 0
for i in range(len(a)):
  dot += a[i] * b[i]
dot

11

In [6]:
a * b

array([3, 8])

In [7]:
np.sum(a * b)

11

In [8]:
(a * b).sum()

11

In [9]:
np.dot(a, b)

11

In [10]:
a.dot(b)

11

In [11]:
b.dot(a)

11

In [12]:
a @ b

11

$$ a^T b = \left\lVert a \right\rVert \left\lVert b \right\rVert \cos \theta_{ab}$$

$$ \cos \theta_{ab} = \frac{a^T b}{\left\lVert a \right\rVert \left\lVert b \right\rVert} $$

## Computing Second Norm of an Array

$$ \left\lVert a \right\rVert = \sqrt{\sum_{d=1}^D a_d^2 } $$

In [13]:
mag = np.sqrt((a * a).sum())
mag

2.23606797749979

In [14]:
mag = np.linalg.norm(mag)
mag

2.23606797749979

In [16]:
cos_angle = a.dot(b) / (np.linalg.norm(a) * np.linalg.norm(b))

In [17]:
cos_angle

0.9838699100999074

In [18]:
angle = np.arccos(cos_angle)
angle

0.17985349979247847

## Speed Test

In [19]:
## speed comparison ##
from datetime import datetime

# note: you can also use %timeit

a = np.random.randn(100)
b = np.random.randn(100)
T = 100000

def slow_dot_product(a, b):
  result = 0
  for e, f in zip(a, b):
    result += e*f
  return result

t0 = datetime.now()
for t in range(T):
  slow_dot_product(a, b)
dt1 = datetime.now() - t0

t0 = datetime.now()
for t in range(T):
  a.dot(b)
dt2 = datetime.now() - t0

print("dt1 / dt2:", dt1.total_seconds() / dt2.total_seconds())

dt1 / dt2: 38.280710387891915


## Matrices

In [54]:
L = [[1,2], [3,4]]
L

[[1, 2], [3, 4]]

In [55]:
L[0]

[1, 2]

In [56]:
L[0][1]

2

In [57]:
A = np.array([[1,2], [3,4]])
A

array([[1, 2],
       [3, 4]])

In [58]:
A[0][1]

2

In [59]:
A[0,1]

2

In [60]:
A[:,0]

array([1, 3])

In [61]:
A.T

array([[1, 3],
       [2, 4]])

In [62]:
np.exp(A)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [63]:
np.exp(L)


array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

Numpy already knows the structure of your List.
If you ever need to pass a list to scipy or numpy, you DO NOT need to convert it to an array.

In [64]:
B = np.array([[1,2,3],[4,5,6]])
B

array([[1, 2, 3],
       [4, 5, 6]])

In [65]:
A.dot(B)

array([[ 9, 12, 15],
       [19, 26, 33]])

In [46]:
C =  np.array([[1,2],[4,5]])

In [67]:
A.dot(A)

array([[ 7, 10],
       [15, 22]])

In [66]:
# error! inner dimensions must match
A.dot(B.T)

ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [68]:
np.linalg.det(A)

-2.0000000000000004

In [69]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [70]:
np.linalg.inv(A).dot(A)

array([[1.00000000e+00, 0.00000000e+00],
       [2.22044605e-16, 1.00000000e+00]])

In [71]:
np.trace(A)

5

In [ ]:
np.diag(A)

In [ ]:
np.diag([1, 4])

In [73]:
np.linalg.eig(A)
# https://en.wikipedia.org/wiki/Eigendecomposition_of_a_matrix

(array([-0.37228132,  5.37228132]),
 array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [74]:
Lam, V = np.linalg.eig(A)

In [75]:
V[:,0] * Lam[0] == A @ V[:,0]

array([ True, False])

In [76]:
V[:,0] * Lam[0], A @ V[:,0]

(array([ 0.30697009, -0.21062466]), array([ 0.30697009, -0.21062466]))

In [77]:
np.allclose(V[:,0] * Lam[0], A @ V[:,0])

True

In [ ]:
np.allclose(V @ np.diag(Lam), A @ V)

## Solving Linear Systems

Cinema:
fee for children: 1500  -> x1
fee for adults: 4000    -> x2
Last Friday: collected fee -> 5050000
All attendees: 2200 people
Question: how many children and how many adults?

$$ Ax = b <=> x = A^{-1}  b $$

In [78]:
A = np.array([[1, 1], [1500, 4000]])
b = np.array([2200, 5050000])

In [79]:
np.linalg.solve(A, b)

array([1500.,  700.])

In [80]:
# don't do this
np.linalg.inv(A).dot(b)

array([1500.,  700.])

np.linalg.solve(A, b) does not compute the inverse of A.
Instead it calls one of the GESV LAPACK routines, which first factorizes A using LU decomposition,
then solves for x using forward and backward substitution.

np.linalg.inv uses the same method to compute the inverse of A by solving for A-1 in A·A-1 = I where I is the identity (eye).
The factorization step is exactly the same as above,
but it takes more floating point operations to solve for A-1 (an n×n matrix) than for x (an n-long vector).
Additionally, if you then wanted to obtain x via the identity A-1·b = x then
the extra matrix multiplication would incur yet more floating point operations,
and therefore slower performance and more numerical error.



GESV LAPACK Routine: https://netlib.org/lapack/double/dgesv.f
LU Decomposition: https://en.wikipedia.org/wiki/LU_decomposition#Solving_linear_equations


## Generating Data

In [ ]:
np.zeros((2, 3))

In [ ]:
np.ones((2, 3))

In [ ]:
10 * np.ones((2, 3))

In [ ]:
np.eye(3)

In [ ]:
np.random.random()

In [ ]:
np.random.random((2, 3))

In [ ]:
np.random.randn(2, 3)

In [ ]:
R = np.random.randn(10000)

In [ ]:
R.mean()

In [ ]:
np.mean(R)

In [ ]:
R.var()

In [ ]:
R = np.random.randn(10000, 3)

In [ ]:
R.mean(axis=0)

In [ ]:
R.mean(axis=1).shape

In [ ]:
np.cov(R).shape

In [ ]:
np.cov(R.T)

In [ ]:
np.cov(R, rowvar=False)

In [ ]:
np.random.randint(0, 10, size=(3, 3))

In [ ]:
np.random.choice(10, size=(3, 3))

In [14]:
import sys
t = (('name', 'Mehdi'), ('age', 25), ('test', 24), ('test1', 76), ('test2', 8687))

sys.getsizeof(dict(t))

232

In [15]:
sys.getsizeof({'name':'Mehdi', 'age': 25, 'test': 24,
               'test1': 76, 'test2': 8687})

232